---
hero_image: images/rate-your-mates.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Beoordeel je vrienden
description: Gebruik je micro:bit om je gemeenschappelijkheid met vrienden te controleren!
original_url: https://codeclubprojects.org/en-GB/microbit/rate-your-mates
interests: ''
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-03-06
steps:
- title: Inleiding
  completion: engaged
- title: Knoppen gelijktijdig indrukken
- title: Een beoordeling laten zien
- title: Beste vrienden
- title: 'Uitdaging: Lage beoordeling'
- title: Een animatie toevoegen
  completion: internal
- title: 'Uitdaging: Meer animaties'
