---
hero_image: images/rate-your-mates.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Rate Your Mates
description: Use your micro:bit to find our your compatibility with friends!
original_url: https://codeclubprojects.org/en-GB/microbit/rate-your-mates
interests: ''
technologies: ''
site_areas: codeclub, microbit
steps:
- title: Introduction
- title: Pressing buttons together
- title: Displaying a rating
- title: Best mates
- title: 'Challenge: Low rating'
- title: Adding an animation
- title: 'Challenge: More animations'

