---
hero_image: images/rate-your-mates.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Graddiwch eich Ffrindiau
description: 'Defnyddiwch eich micro: bit i ganfod eich cydnawsedd â ffrindiau!'
original_url: https://codeclubprojects.org/en-GB/microbit/rate-your-mates
interests: ''
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - title: Cyflwyniad
  - title: Pwyso botymau gyda'i gilydd
  - title: Dangos gradd
  - title: Ffrindiau gorau
  - title: 'Her: Gradd isel'
  - title: Ychwanegu animeiddiad
  - title: 'Her: Mwy o animeiddiadau'
