---
hero_image: images / rate-your-mates.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, disseny-0, programació-1, phys-comp-0, fabricació-0, comunitat-0
title: Rate Your Mates
description: Use your micro:bit to find out your compatibility with friends!
original_url: https://codeclubprojects.org/en-GB/microbit/rate-your-mates
interests: ''
technologies: microbit
site_areas: projectes
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-03-06
steps:
  - 
    title: Introducció
  - 
    title: Pressing buttons together
  - 
    title: Displaying a rating
  - 
    title: Best mates
  - 
    title: 'Challenge: Low rating'
  - 
    title: Adding an animation
  - 
    title: 'Challenge: More animations'
