---
hero_image: images/rate-your-mates.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Califica a tus compañeros
description: "¡Utiliza tu micro:bit para encontrar tu compatibilidad con amigos!"
original_url: https://codeclubprojects.org/en-GB/microbit/rate-your-mates
interests: ''
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-03-06
steps:
- title: Introducción
  completion: engaged
- title: Presionar ambas teclas juntas
- title: Mostrar una calificación
- title: Mejores compañeros
- title: 'Desafío: Puntuación baja'
- title: Agregar una animación
  completion: internal
- title: 'Desafío: Más animaciones'
