---
hero_image: images/rate-your-mates.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, 디자인 -0, 프로그래밍 -1, phys-comp-0, 제조 -0, 커뮤니티 -0
title: Rate Your Mates
description: Use your micro:bit to find out your compatibility with friends!
original_url: https://codeclubprojects.org/en-GB/microbit/rate-your-mates
interests: ''
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-03-06
steps:
  - 
    title: 소개
  - 
    title: Pressing buttons together
  - 
    title: Displaying a rating
  - 
    title: Best mates
  - 
    title: 'Challenge: Low rating'
  - 
    title: Adding an animation
  - 
    title: 'Challenge: More animations'
