---
hero_image: images/rate-your-mates.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Βαθμός Φιλίας
description: Χρησιμοποίησε το micro:bit για να μάθεις τη συμβατότητά με τους φίλους σου!
original_url: https://codeclubprojects.org/en-GB/microbit/rate-your-mates
interests: ''
technologies: '   microbit'
site_areas: projects
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-03-06
steps:
  - title: Εισαγωγή
  - title: Πατάμε τα κουμπιά μαζί
  - title: Προβολή βαθμολογίας
  - title: Οι καλύτεροι φίλοι
  - title: 'Πρόκληση: Χαμηλή βαθμολογία'
  - title: Προσθήκη κινούμενης εικόνας
  - title: 'Πρόκληση: Περισσότερες κινούμενες εικόνες'
