---
hero_image: images/rate-your-mates.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Note tes amis
description: Utiliser ton micro:bit pour trouver ta compatibilité avec tes amis !
original_url: https://codeclubprojects.org/en-GB/microbit/rate-your-mates
interests: ''
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-03-06
steps:
  - 
    title: Introduction
  - 
    title: Appuyer sur les deux boutons ensemble
  - 
    title: Afficher la note
  - 
    title: Les meilleurs amis
  - 
    title: 'Défi : Faible note'
  - 
    title: Ajouter des animations
  - 
    title: 'Défi : Plus d''animations'
