---
hero_image: images/rate-your-mates.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmation-1, phys-comp-0, fabrication-0, communauté-0
title: Note tes potes
description: Utilise ton micro:bit pour trouver ta compatibilité avec tes amis !
original_url: https://codeclubprojects.org/en-GB/microbit/rate-your-mates
interests: ''
technologies: microbit
site_areas: projets
hardware: microbit
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Appuyer sur les deux boutons ensemble
  - 
    title: Afficher la note
  - 
    title: Les meilleurs potes
  - 
    title: 'Défi : Mauvaise note'
  - 
    title: Ajouter des animations
  - 
    title: 'Défi : Plus d''animations'
